export const COMPONENT_FILE_HEADER =
`/**
 * {%%KONG_COMPONENT_FILENAME%%}
 * This file was generated via the build script. Do not edit this file directly.
 * Generated on ${new Date().toUTCString()}
 *
 * GitHub: https://github.com/Kong/icons
 * License: Apache-2.0
 */
`

export const COMPONENTS_INDEX_FILE_HEADER =
`/**
 * This file was generated via the build script. Do not edit this file directly.
 * Generated on ${new Date().toUTCString()}
 *
 * GitHub: https://github.com/Kong/icons
 * License: Apache-2.0
 */
`
