export const COMPONENT_FILE_HEADER =
`/**
 * {%%KONG_GENERATED_FILENAME%%}
 * This file was generated via the build script. Do not edit this file directly.
 * Generated on ${new Date().toUTCString()}
 *
 * GitHub: https://github.com/Kong/icons
 * License: Apache-2.0
 */
`

export const TS_FILE_HEADER =
`/**
 * This file was generated via the build script. Do not edit this file directly.
 * Generated on ${new Date().toUTCString()}
 *
 * GitHub: https://github.com/Kong/icons
 * License: Apache-2.0
 */
`

export const COMPONENT_LIST_FILE_HEADER =
`/**
 * This components list is updated whenever a new version is published, and
 * tracks the list of components that are exported from the package.
 *
 * If components are removed from this list (meaning they are
 * no longer exported from the package), it is likely a breaking
 * change which should trigger a new major package version release.
 * The major version should be incremented by utilizing a conventional
 * commit message with \`BREAKING CHANGE:\` text in the commit footer.
 */
`
