<script lang="ts" setup>
/**
 * This file was generated via the build script. Do not edit this file directly.
 * Generated on Fri, 07 Jul 2023 01:03:09 GMT
 *
 * GitHub: https://github.com/Kong/icons
 * License: Apache-2.0
 */

defineProps({
  title: {
    type: String,
    required: false,
    default: '',
  },
  decorative: {
    type: Boolean,
    required: false,
    default: false,
  },
  size: {
    type: Number,
    required: false,
    default: 24, // TODO: Replace with a token
  },
})
</script>

<template>
  <span class="kui-icon">
    <svg
      :aria-hidden="decorative ? true : false"
      aria-labelledby="theTitle"
      fill="none"
      :height="String(size)"
      role="img"
      viewBox="0 0 24 24"
      :width="String(size)"
      xmlns="http://www.w3.org/2000/svg"
    >
      <title v-if="title">{{ title }}</title>
      <path
        clipRule="evenodd"
        d="M12 17C12.2833 17 12.5208 16.9042 12.7125 16.7125C12.9042 16.5208 13 16.2833 13 16C13 15.7167 12.9042 15.4792 12.7125 15.2875C12.5208 15.0958 12.2833 15 12 15C11.7167 15 11.4792 15.0958 11.2875 15.2875C11.0958 15.4792 11 15.7167 11 16C11 16.2833 11.0958 16.5208 11.2875 16.7125C11.4792 16.9042 11.7167 17 12 17ZM11 13H13V7H11V13ZM12 22C10.6167 22 9.31667 21.7375 8.1 21.2125C6.88333 20.6875 5.825 19.975 4.925 19.075C4.025 18.175 3.3125 17.1167 2.7875 15.9C2.2625 14.6833 2 13.3833 2 12C2 10.6167 2.2625 9.31667 2.7875 8.1C3.3125 6.88333 4.025 5.825 4.925 4.925C5.825 4.025 6.88333 3.3125 8.1 2.7875C9.31667 2.2625 10.6167 2 12 2C13.3833 2 14.6833 2.2625 15.9 2.7875C17.1167 3.3125 18.175 4.025 19.075 4.925C19.975 5.825 20.6875 6.88333 21.2125 8.1C21.7375 9.31667 22 10.6167 22 12C22 13.3833 21.7375 14.6833 21.2125 15.9C20.6875 17.1167 19.975 18.175 19.075 19.075C18.175 19.975 17.1167 20.6875 15.9 21.2125C14.6833 21.7375 13.3833 22 12 22Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  </span>
</template>

<style lang="scss" scoped>
.kui-icon {
  box-sizing: border-box;
  color: currentColor;
  display: block;
  height: $kui-font-size-60;
  line-height: 0;
  width: $kui-font-size-60;
}
</style>
