<script lang="ts" setup>
/**
 * This file was generated via the build script. Do not edit this file directly.
 * Generated on Fri, 07 Jul 2023 01:03:09 GMT
 *
 * GitHub: https://github.com/Kong/icons
 * License: Apache-2.0
 */

defineProps({
  title: {
    type: String,
    required: false,
    default: '',
  },
  decorative: {
    type: Boolean,
    required: false,
    default: false,
  },
  size: {
    type: Number,
    required: false,
    default: 24, // TODO: Replace with a token
  },
})
</script>

<template>
  <span class="kui-icon">
    <svg
      :aria-hidden="decorative ? true : false"
      aria-labelledby="theTitle"
      fill="none"
      :height="String(size)"
      role="img"
      viewBox="0 0 24 24"
      :width="String(size)"
      xmlns="http://www.w3.org/2000/svg"
    >
      <title v-if="title">{{ title }}</title>
      <path
        clipRule="evenodd"
        d="M4 20V3H13L13.4 5H19V15H12L11.6 13H6V20H4ZM13.65 13H17V7H11.75L11.35 5H6V11H13.25L13.65 13Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  </span>
</template>

<style lang="scss" scoped>
.kui-icon {
  box-sizing: border-box;
  color: currentColor;
  display: block;
  height: $kui-font-size-60;
  line-height: 0;
  width: $kui-font-size-60;
}
</style>
