<script lang="ts" setup>
/**
 * This file was generated via the build script. Do not edit this file directly.
 * Generated on Fri, 07 Jul 2023 01:03:09 GMT
 *
 * GitHub: https://github.com/Kong/icons
 * License: Apache-2.0
 */

defineProps({
  title: {
    type: String,
    required: false,
    default: '',
  },
  decorative: {
    type: Boolean,
    required: false,
    default: false,
  },
  size: {
    type: Number,
    required: false,
    default: 24, // TODO: Replace with a token
  },
})
</script>

<template>
  <span class="kui-icon">
    <svg
      :aria-hidden="decorative ? true : false"
      aria-labelledby="theTitle"
      fill="none"
      :height="String(size)"
      role="img"
      viewBox="0 0 24 24"
      :width="String(size)"
      xmlns="http://www.w3.org/2000/svg"
    >
      <title v-if="title">{{ title }}</title>
      <path
        clipRule="evenodd"
        d="M9.92421 2.3999L5.76021 9.5999H18.2402L12.0002 20.3999L5.76021 9.5999L1.51221 16.9679L3.67221 20.3999H21.2402L22.8482 17.5919L14.0882 2.3999H9.91221H9.92421Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  </span>
</template>

<style lang="scss" scoped>
.kui-icon {
  box-sizing: border-box;
  color: currentColor;
  display: block;
  height: $kui-font-size-60;
  line-height: 0;
  width: $kui-font-size-60;
}
</style>
