<script lang="ts" setup>
/**
 * This file was generated via the build script. Do not edit this file directly.
 * Generated on Thu, 06 Jul 2023 23:51:32 GMT
 */
defineProps({
  title: {
    type: String,
    required: false,
    default: '',
  },
  decorative: {
    type: Boolean,
    required: false,
    default: false,
  },
  size: {
    type: Number,
    required: false,
    default: 24, // TODO: Replace with a token
  },
})
</script>

<template>
  <span class="kui-icon">
    <svg
      :aria-hidden="decorative ? true : false"
      aria-labelledby="theTitle"
      fill="none"
      :height="String(size)"
      role="img"
      viewBox="0 0 24 24"
      :width="String(size)"
      xmlns="http://www.w3.org/2000/svg"
    >
      <title v-if="title">{{ title }}</title>
      <path
        clipRule="evenodd"
        d="M3 21V3H21V21H3ZM5 9H19V5H5V9ZM10.325 14H13.675V11H10.325V14ZM10.325 19H13.675V16H10.325V19ZM5 14H8.325V11H5V14ZM15.675 14H19V11H15.675V14ZM5 19H8.325V16H5V19ZM15.675 19H19V16H15.675V19Z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  </span>
</template>

<style lang="scss" scoped>
.kui-icon {
  box-sizing: border-box;
  color: currentColor;
  display: block;
  height: $kui-font-size-60;
  line-height: 0;
  width: $kui-font-size-60;
}
</style>
