/**
 * This components list is updated whenever a new version is published, and
 * tracks the list of components that are exported from the package.
 *
 * If components are removed from this list (meaning they are
 * no longer exported from the package), it is likely a breaking
 * change which should trigger a new major package version release.
 * The major version should be incremented by utilizing a conventional
 * commit message with `BREAKING CHANGE:` text in the commit footer.
 * Generated on Fri, 14 Jul 2023 00:42:12 GMT
 */

export default [
  'AddCircleIcon.vue',
  'AddIcon.vue',
  'ArrowDownIcon.vue',
  'ArrowLeftIcon.vue',
  'ArrowRightIcon.vue',
  'ArrowUpIcon.vue',
  'AwsIcon.vue',
  'AzureIcon.vue',
  'BackIcon.vue',
  'BarChartIcon.vue',
  'BookIcon.vue',
  'BotIcon.vue',
  'BrainIcon.vue',
  'CalIcon.vue',
  'CheckCircleIcon.vue',
  'CheckIcon.vue',
  'CheckSmallIcon.vue',
  'ChevronDownIcon.vue',
  'ChevronLeftIcon.vue',
  'ChevronRightIcon.vue',
  'ChevronUpIcon.vue',
  'ClearIcon.vue',
  'ClipboardIcon.vue',
  'ClockIcon.vue',
  'CloseIcon.vue',
  'CloudIcon.vue',
  'CogIcon.vue',
  'CollapseIcon.vue',
  'CollapsePanelIcon.vue',
  'ConnectionsIcon.vue',
  'CopyIcon.vue',
  'DangerCircleIcon.vue',
  'DashboardIcon.vue',
  'DeployIcon.vue',
  'DevPortalIcon.vue',
  'DisabledIcon.vue',
  'DocumentIcon.vue',
  'DocumentListIcon.vue',
  'DragIcon.vue',
  'EditIcon.vue',
  'EuropeanUnionIcon.vue',
  'ExpandIcon.vue',
  'ExternalLinkIcon.vue',
  'FeatureRequestIcon.vue',
  'FileEmptyIcon.vue',
  'FilterIcon.vue',
  'FlagIcon.vue',
  'GoogleCloudIcon.vue',
  'GoogleIcon.vue',
  'GraduationIcon.vue',
  'GridIcon.vue',
  'HelpIcon.vue',
  'ImageIcon.vue',
  'InboxIcon.vue',
  'IndeterminateSmallIcon.vue',
  'InfoIcon.vue',
  'KongIcon.vue',
  'ListIcon.vue',
  'LockIcon.vue',
  'MeshIcon.vue',
  'MoreHorizontalIcon.vue',
  'MoreIcon.vue',
  'NotificationIcon.vue',
  'OverviewIcon.vue',
  'PeopleIcon.vue',
  'PlugIcon.vue',
  'PortalIcon.vue',
  'PresentationIcon.vue',
  'ProfileIcon.vue',
  'RedoIcon.vue',
  'RuntimeCompositeIcon.vue',
  'RuntimeDedicatedCloudIcon.vue',
  'RuntimeHybridIcon.vue',
  'RuntimeKicIcon.vue',
  'RuntimesIcon.vue',
  'SearchIcon.vue',
  'SecurityIcon.vue',
  'ServiceDocumentIcon.vue',
  'ServiceHubIcon.vue',
  'ServicesIcon.vue',
  'SharedIcon.vue',
  'SupportIcon.vue',
  'TableIcon.vue',
  'TeammateIcon.vue',
  'TrashIcon.vue',
  'UnitedStatesIcon.vue',
  'VitalsIcon.vue',
  'WarningIcon.vue',
  'WorldIcon.vue',
]
